# Generated by Django 3.0.4 on 2020-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200409_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='formHtml',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
