# Generated by Django 3.0.4 on 2020-04-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formtemplate_formhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='formHtml',
        ),
    ]
