# Generated by Django 3.0.4 on 2020-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formtemplate_formhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='formHtml',
            field=models.TextField(blank=True),
        ),
    ]
