# Generated by Django 3.0.4 on 2020-04-03 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalHierarchy',
            fields=[
                ('nodeId', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nodeName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('roleId', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=150)),
                ('postFlag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.RoleHierarchy')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
