# Generated by Django 3.0.4 on 2020-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.CharField(max_length=150, unique=True)),
                ('roleName', models.CharField(max_length=150)),
                ('postFlag', models.BooleanField()),
            ],
        ),
    ]
