# Generated by Django 2.1.2 on 2020-04-06 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schema', '0002_fieldschema_modelschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startFrom', models.DateField(blank=True, null=True)),
                ('endTo', models.DateField(blank=True, null=True)),
                ('nodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.DepartmentalHierarchy')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
