# Generated by Django 2.1.2 on 2020-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalhierarchy',
            name='isLeaf',
            field=models.BooleanField(default=False),
        ),
    ]
